### ISSUE TITLE
install Error

### ISSUE THREAD

**Issue by FLNDTORRES** [SConsProject/scons#4066]
Hi, after i install it， i can't find scons command

![4510ed34d62430f2a049202468cd08e](https://user-images.githubusercontent.com/26167791/143580830-5627d431-7eac-41f9-a453-49196c138a92.png)

**Comment by mwichmann** [comment]
Don't install that way.  Use pip to install:
```bash
python -m pip install --user scons
```

Problems with the above:

- per the Python Packaging Authority, the tooling (pip, setuptools, etc.) does not properly support direct invocations of setup.py any longer.
- the SCons project doesn't recommend it either
- By using `sudo` you're "forcing" this issue and just causing problems
- You might check if your distribution has a packaged scons, that would be a way to do a "system-level" installation.

Something is broken in your log since it keeps saying UNKNOWN - no way from here to really tell what happened.

**Comment by bdbaddog** [comment]
From the log you posted, it looks like it's installed in /usr/local/bin
So try there.

Also this is not a recommended (or supported) way to install SCons.
Don't sudo python setup.py anything on your system. That's pretty much always a very bad idea.

The preferred install method is to create a python virtualenv, and use pip to install SCons in that virtualenv.

Closing.
