### ISSUE TITLE
ParseConfig can fail when adding to CPPDEFINES

### ISSUE THREAD

**Issue by mwichmann** [SConsProject/scons#4321]
After the changes in `CPPDEFINES` handling for SCons 4.5, it is possible for `ParseConfig` to hit a `TypeError`. Here is one traceback:
```py
TypeError: sequence index must be integer, not 'slice':
  File "/home/akien/Projects/godot/godot.git/SConstruct", line 539:
    detect.configure(env)
  File "/home/akien/Projects/godot/godot.git/./platform/linuxbsd/detect.py", line 309:
    env.ParseConfig("pkg-config libpulse --cflags --libs")
  File "/home/akien/.local/lib/python3.10/site-packages/SCons/Environment.py", line 1773:
    return function(self, self.backtick(command), unique)
  File "/home/akien/.local/lib/python3.10/site-packages/SCons/Environment.py", line 1767:
    return env.MergeFlags(cmd, unique)
  File "/home/akien/.local/lib/python3.10/site-packages/SCons/Environment.py", line 1095:
    for v in orig[::-1]:
```

For this condition to trigger, `CPPDEFINES` in that environment must have previously been converted into the internal `deque` type. The error actually happens in `MergeFlags`, which tries to do various complicated things to simulate what the `Append` routine would do in adding.  Since `Append` and relatives now short-circuits that work in case the key is `CPPDEFINES`, it seems `MergeFlags` should do the same.

**Comment by akien-mga** [comment]
Attaching a minimal reproduction project, which reproduces the issue with 4.5.0 and 4.5.1:
[scons-ParseConfig-CPPDEFINES-merge.zip](https://github.com/SCons/scons/files/10933228/scons-ParseConfig-CPPDEFINES-merge.zip)

**Comment by mwichmann** [comment]
I'm seeing another hole here, I think - `env.Override(parse_flags={some: dict})` seems to not give an independent value. Investigating - this tripped on an existing testcase after a change for the above.

**Comment by bdbaddog** [comment]
ok. Once we have a fix for both, we can roll a 4.5.2

**Comment by mwichmann** [comment]
Sigh, it looks like (without documenting it), `MergeFlags`  always creates a new item, so my short-circuit means that doesn't happen, and so indeed that opens up a new leak-through

**Comment by mwichmann** [comment]
@akien-mga - the patch proposed in the PR ended up being different, because of the new problem that one created.  Would you be able to test the change from `SCons/Environment.py` in your setup to make sure it still works for you?

**Comment by akien-mga** [comment]
@mwichmann I confirm that #4322 (as of e58b9c382ddf00c48027a9610589a59062ecce70) fixes the bug for me, applied the diff manually on top of pip-installed 4.5.1.

**Comment by mwichmann** [comment]
Not going to tackle this here, as want to keep this PR as a simple "hotfix", but don't actually see any reason why `MergeFlags` needs to reimplement the adding logic (it contains the comment `The logic here was lifted from part of env.Append() `) - we've already proven here that having it in two places makes it more fragile. So someday... at that point, the caller should end up indicating whether the variables merged into need to be independent (`Override` case) or the existing environment vars can be safely updated (all other callers, AFAICT).

**Comment by mgorny** [comment]
Could you please make a new release with this fix? This is affecting at least godot on Gentoo, and quite likely dxx-rebirth (I haven't confirmed whether it's the same cause).

**Comment by bdbaddog** [comment]
> Could you please make a new release with this fix? This is affecting at least godot on Gentoo, and quite likely dxx-rebirth (I haven't confirmed whether it's the same cause).

IRL issues causing delay. I'll try to get it out today sometime.

**Comment by bdbaddog** [comment]
4.5.2 released.

**Comment by mgorny** [comment]
Thank you!

**Comment by arbruijn** [comment]
There's still a deque returned by env['CPPDEFINES'] in 4.5.2 after env.Append with an existing and added list, which can break SConstruct files. The documentation seems to suggest it should result in a list ([7.2.10. Appending to the End of Values: the Append Method](https://scons.org/doc/production/HTML/scons-user/ch07s02.html#idp105548963833800)). Is this an intended change of behavior?

Example that worked before 4.5.0 and breaks since 4.5.0:
```py
env = Environment()
env.Append(CPPDEFINES = ['A'])
env.Append(CPPDEFINES = ['B'])
defs = env['CPPDEFINES'] + ['X']
```

**Comment by mwichmann** [comment]
It was an intended change.  What type it is is supposed to be internal, and works consistently internally, *but* there's not much to be done if the API methods for amending are not used - adding an object directly using Python syntax.  May have to give up on deque (it was chosen because the `Prepend` methods then work as cleanly as the `Append` methods without resorting to tricks - *one* of the instances in the old version, but not all, reversed, added, reversed again to Prepend).

Note that whatever that snip in the user guide says, the internal represntation was *never* guaranteed, and could change depending on what operations you performed.  Using a different pathway of building up `CPPDEFINES` you could have ended up with a dict, and then your same add would fail (hypothetical example, but I ran through lots of these permutations when I expanded the tests):
```py
emv = Environment()
env.Append(CPPDEFINES={'A': None, 'B': None})
defs = env['CPPDEFINES'] + ['X']
```
would take an exception
```py
TypeError: unsupported operand type(s) for +: 'dict' and 'list'
```

**Comment by vLKp** [comment]
Regarding https://github.com/SCons/scons/issues/4321#issuecomment-1477305109 :

>  This is affecting at least godot on Gentoo, and quite likely dxx-rebirth (I haven't confirmed whether it's the same cause).

I think the Rebirth problem was caused by the same SCons change that broke ParseConfig, but the failure mode is different, and I think the change in https://github.com/SCons/scons/commit/a4ab466c6df5bd3187e78c36bfa8f68e1fb7659e would not help Rebirth.  Rebirth had an expression of the form `env.get(name, [])[:]`, which sought to look up a variable from the construction environment and create a copy of it.  When the construction environment returned a Python `list`, `[:]` worked.  Now that SCons returns a Python `deque`, the error reported in https://github.com/dxx-rebirth/dxx-rebirth/issues/704 occurs, because `deque` does not understand using `[:]` to create a copy.  I changed that expression to `env.get(name, []).copy()`, which works just as well on SCons 4.4.  I have not tried it on SCons 4.5 yet (scons is not slotted, and I am not ready to remove SCons 4.4 yet), but I published the change in the hope that it would be useful.
